# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy

builds:
  - id: mackerel-plugin-puma-v2
    main: ./cmd/mackerel-plugin-puma-v2
    binary: mackerel-plugin-puma-v2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: mackerel-plugin-puma-v2
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # Use zip format for all platforms (required by mkr)
    format: zip
    # Only include the binary, not the directory structure
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: srockstyle
    name: mackerel-plugin-puma-v2
  
  # Don't skip upload for future releases
  # skip_upload: true
  
  # If set to false, an existing release will be updated.
  # This is useful if you want to update the release notes or upload new assets
  replace_existing_draft: false
  
  # Header for the release notes
  header: |
    ## mackerel-plugin-puma-v2 {{.Tag}}

    {{.TagSubject}}